version: '3.9'

services:
  web:
    build: .
    container_name: tramplanner_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env



  # frontend:
  #   build:
  #     context: ./config/static/frontend
  #   container_name: tramplanner-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - web
