version: '3.9'

services:
  web:
    build:
      context: ./backend
    container_name: tramplanner-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: sqlite
    container_name: sqlite-db
    volumes:
      - ./sqlite_data:/data

  # frontend:
  #   build:
  #     context: ./config/static/frontend
  #   container_name: tramplanner-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - web
