# Generated by Django 5.2.1 on 2025-05-29 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de réponse'), ('accepte_agent', "Accepté par l'agent"), ('refuse_agent', "Refusé par l'agent"), ('valide_superviseur', 'Validé par le superviseur'), ('refuse_superviseur', 'Refusé par le superviseur'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('message_demandeur', models.TextField(blank=True, help_text="Raison de la demande d'échange", null=True, verbose_name='Message du demandeur')),
                ('commentaire_destinataire', models.TextField(blank=True, null=True, verbose_name='Commentaire du destinataire')),
                ('commentaire_superviseur', models.TextField(blank=True, null=True, verbose_name='Commentaire du superviseur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date_reponse_agent', models.DateTimeField(blank=True, null=True, verbose_name='Date réponse agent')),
                ('date_decision_superviseur', models.DateTimeField(blank=True, null=True, verbose_name='Date décision superviseur')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('planning_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_echange_demandeur', to='planning_app.planning', verbose_name='Planning du demandeur')),
                ('planning_destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_echange_destinataire', to='planning_app.planning', verbose_name='Planning du destinataire')),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Superviseur')),
            ],
            options={
                'verbose_name': "Demande d'échange",
                'verbose_name_plural': "Demandes d'échange",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='exchanges.demandeechange')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
