# Generated by Django 5.2.1 on 2025-06-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='poste',
            field=models.CharField(blank=True, help_text='Code du poste (ex: 31, 750, R, CCF...)', max_length=10, null=True, verbose_name='Poste de travail'),
        ),
    ]
